version: '3.7'

services: 
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - ENVIRONMENT = ${ENVIRONMENT} 
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=0
      - DEFAULT_FROM_MAIL = ${DEFAULT_FROM_MAIL}
      - STRIPE_TEST_PUBLISHABLE_KEY = ${STRIPE_TEST_PUBLISHABLE_KEY}
    volumes: 
      - .:/code
    ports: 
      - 8000:8000
    depends_on: 
      - db
    env_file:
      - .env
  
  db:
    image: postgres:11
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes: 
  postgres_data: